### ISSUE TITLE
Exception encountered, of type "Error"

### ISSUE THREAD

**Issue by rabin-io** [mediawiki4intranet/Dia#3]
I get the above error when trying to use this extension with mediawiki 1.27 and PHP7.

    Exception encountered, of type "Error"

**Comment by vitalif** [comment]
cool. but pls provide some details. you can get them by enabling stack traces or debug logging in localsettings.php.

**Comment by rabin-io** [comment]
Here you go, 

```
Exception encountered, of type "Error"
[fcc0f8de46785733b578d97e] /File:Schema.dia Error from line 251 of /www/mediawiki-1.27.0/extensions/Dia/Dia.body.php: Call to undefined function wfMsg()
Backtrace:
#0 /www/mediawiki-1.27.0/includes/filerepo/file/File.php(2169): DiaHandler->getLongDesc(LocalFile)
#1 /www/mediawiki-1.27.0/includes/page/ImagePage.php(517): File->getLongDesc()
#2 /www/mediawiki-1.27.0/includes/page/ImagePage.php(159): ImagePage->openShowImage()
#3 /www/mediawiki-1.27.0/includes/actions/ViewAction.php(44): ImagePage->view()
#4 /www/mediawiki-1.27.0/includes/MediaWiki.php(503): ViewAction->show()
#5 /www/mediawiki-1.27.0/includes/MediaWiki.php(288): MediaWiki->performAction(ImagePage, Title)
#6 /www/mediawiki-1.27.0/includes/MediaWiki.php(745): MediaWiki->performRequest()
#7 /www/mediawiki-1.27.0/includes/MediaWiki.php(519): MediaWiki->main()
#8 /www/mediawiki-1.27.0/index.php(43): MediaWiki->run()
#9 {main}
```

**Comment by rabin-io** [comment]
Hello, Can this problem be easily resolved ? 
or it will takes some time to come with a prober solution ?

**Comment by vitalif** [comment]
I've committed the fix, ok.

> and the page will now load, but can't see the picture.

Try to "purge" the image page (?action=purge). It should regenerate the thumbnail...

**Comment by rabin-io** [comment]
Thanks for the update, but it didn't solve my problem. I get the page but **without** the picture.
(even after accessing the page with `?action=purge`)

**Comment by vitalif** [comment]
No, I didn't. I thought mediawiki cached the error (it happens sometimes) :-) did you purge the image page or article in which it was inserted? You should try the first i.e File:x.dia?action=purge

**Comment by rabin-io** [comment]
Yes I did try first purging the image page (and you can "fill" it working by the time it takes for the page to render), but in the end I get a blank image (the wiki page it self did load but w/o the picture).

**Comment by vitalif** [comment]
ok, what's the problem then?
I've checked Dia with 1.27, it works on my PC.

**Comment by rabin-io** [comment]
Did you create a new patch for this version ?

**Comment by vitalif** [comment]
No, I'm using the latest master with the committed fix

**Comment by rabin-io** [comment]
Are using any other extensions ?
